package ServerApp;


/**
* ServerApp/ServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Wednesday, June 23, 2021 2:15:39 PM CST
*/

public abstract class ServerPOA extends org.omg.PortableServer.Servant
 implements ServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createTRecord", new Integer (0));
    _methods.put ("createSRecord", new Integer (1));
    _methods.put ("getRecordCounts", new Integer (2));
    _methods.put ("editRecord", new Integer (3));
    _methods.put ("transferRecord", new Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ServerApp/Server/createTRecord
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String specialization = in.read_string ();
         String location = in.read_string ();
         String managerID = in.read_string ();
         String $result = null;
         $result = this.createTRecord (firstName, lastName, address, phone, specialization, location, managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ServerApp/Server/createSRecord
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String courseRegistered = in.read_string ();
         String status = in.read_string ();
         String statusDate = in.read_string ();
         String managerID = in.read_string ();
         String $result = null;
         $result = this.createSRecord (firstName, lastName, courseRegistered, status, statusDate, managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  /*
        if MTL has 6 records, LVL has 7 and DDO had 8, it should return the following: MTL 6, LVL 7, DDO 8.
         */
       case 2:  // ServerApp/Server/getRecordCounts
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.getRecordCounts (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ServerApp/Server/editRecord
       {
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String managerID = in.read_string ();
         String $result = null;
         $result = this.editRecord (recordID, fieldName, newValue, managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ServerApp/Server/transferRecord
       {
         String managerID = in.read_string ();
         String recordID = in.read_string ();
         String remoteCenterServerName = in.read_string ();
         String $result = null;
         $result = this.transferRecord (managerID, recordID, remoteCenterServerName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServerApp/Server:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Server _this() 
  {
    return ServerHelper.narrow(
    super._this_object());
  }

  public Server _this(org.omg.CORBA.ORB orb) 
  {
    return ServerHelper.narrow(
    super._this_object(orb));
  }


} // class ServerPOA
