
package main.webservice.lvl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "centerService", targetNamespace = "http://com.zexin", wsdlLocation = "http://localhost:8888/LVLServer?wsdl")
public class CenterService
    extends Service
{

    private final static URL CENTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CENTERSERVICE_EXCEPTION;
    private final static QName CENTERSERVICE_QNAME = new QName("http://com.zexin", "centerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/LVLServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CENTERSERVICE_WSDL_LOCATION = url;
        CENTERSERVICE_EXCEPTION = e;
    }

    public CenterService() {
        super(__getWsdlLocation(), CENTERSERVICE_QNAME);
    }

    public CenterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CENTERSERVICE_QNAME, features);
    }

    public CenterService(URL wsdlLocation) {
        super(wsdlLocation, CENTERSERVICE_QNAME);
    }

    public CenterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CENTERSERVICE_QNAME, features);
    }

    public CenterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CenterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CenterServer
     */
    @WebEndpoint(name = "servicePort")
    public CenterServer getServicePort() {
        return super.getPort(new QName("http://com.zexin", "servicePort"), CenterServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CenterServer
     */
    @WebEndpoint(name = "servicePort")
    public CenterServer getServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.zexin", "servicePort"), CenterServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CENTERSERVICE_EXCEPTION!= null) {
            throw CENTERSERVICE_EXCEPTION;
        }
        return CENTERSERVICE_WSDL_LOCATION;
    }

}
