
package main.webservice.lvl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerImpl", targetNamespace = "http://server.main/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerImpl {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTRecord", targetNamespace = "http://server.main/", className = "client.CreateTRecord")
    @ResponseWrapper(localName = "createTRecordResponse", targetNamespace = "http://server.main/", className = "client.CreateTRecordResponse")
    @Action(input = "http://server.main/ServerImpl/createTRecordRequest", output = "http://server.main/ServerImpl/createTRecordResponse")
    public String createTRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editRecord", targetNamespace = "http://server.main/", className = "client.EditRecord")
    @ResponseWrapper(localName = "editRecordResponse", targetNamespace = "http://server.main/", className = "client.EditRecordResponse")
    @Action(input = "http://server.main/ServerImpl/editRecordRequest", output = "http://server.main/ServerImpl/editRecordResponse")
    public String editRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSRecord", targetNamespace = "http://server.main/", className = "client.CreateSRecord")
    @ResponseWrapper(localName = "createSRecordResponse", targetNamespace = "http://server.main/", className = "client.CreateSRecordResponse")
    @Action(input = "http://server.main/ServerImpl/createSRecordRequest", output = "http://server.main/ServerImpl/createSRecordResponse")
    public String createSRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transferRecord", targetNamespace = "http://server.main/", className = "client.TransferRecord")
    @ResponseWrapper(localName = "transferRecordResponse", targetNamespace = "http://server.main/", className = "client.TransferRecordResponse")
    @Action(input = "http://server.main/ServerImpl/transferRecordRequest", output = "http://server.main/ServerImpl/transferRecordResponse")
    public String transferRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecordCounts", targetNamespace = "http://server.main/", className = "client.GetRecordCounts")
    @ResponseWrapper(localName = "getRecordCountsResponse", targetNamespace = "http://server.main/", className = "client.GetRecordCountsResponse")
    @Action(input = "http://server.main/ServerImpl/getRecordCountsRequest", output = "http://server.main/ServerImpl/getRecordCountsResponse")
    public String getRecordCounts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
